version: 2.1

references:
  production: &production
    filters:
      branches:
        only:
          - staging

orbs:
  node: circleci/node@1.1.6
jobs:
  test-build-and-publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: git config --global user.email "harrisonhenrisn@gmail.com"
            - run: git config --global user.name "HarrisonHenri"
            - run: yarn install
            - run: chown $(whoami):$(whoami) -R .
            - run: yarn semantic-release

workflows:
  test-build-and-publish:
    jobs:
      - test-build-and-publish:
          <<: *production
