version: 2.1

references:
  production: &production
    filters:
      branches:
        only:
          - master

orbs:
  android: circleci/android@0.2.0
  node: circleci/node@1.1.6
jobs:
  test-build-and-publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn semantic-release
  zumba:
    executor:
      name: android/android
    steps:
      - checkout
      - run:
          name: Install bundle
          command: bundle install

workflows:
  test-build-and-publish:
    jobs:
      - zumba:
          <<: *production
      - test-build-and-publish:
          <<: *production
          requires:
            - zumba
