version: 2.1

references:
  production: &production
    filters:
      branches:
        only:
          - staging

orbs:
  node: circleci/node@1.1.6
jobs:
  test-build-and-publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: git config --global user.email "harrisonhenrisn@gmail.com"
            - run: git config --global user.name "HarrisonHenri"
            - run: yarn install
            - run: yarn standard-version --release-as minor
            - run: PACKAGE_VERSION=v$(node -pe "require('./package.json')['version']") && echo $PACKAGE_VERSION
            - run: git add .
            - run: git commit -m "chore(release) [ci skip]"
            - run: git tag $PACKAGE_VERSION
            - run: git push -q https://${GITHUB_TOKEN}@github.com/HarrisonHenri/myskills.git staging --tags

workflows:
  test-build-and-publish:
    jobs:
      - test-build-and-publish:
          <<: *production
