version: 2.1

references:
  production: &production
    filters:
      branches:
        only:
          - staging

orbs:
  node: circleci/node@1.1.6
jobs:
  test-build-and-publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - add_ssh_keys:
              fingerprints:
                - "f2:d9:82:2a:46:c7:7c:89:f8:e3:d2:02:15:2d:d3:ad"
            - run:
                command: git config --global user.email "harrisonhenrisn@gmail.com"
            - run:
                command: git config --global user.name "HarrisonHenri"
            - run:
                command: yarn install
            - run:
                command: yarn standard-version --release-as minor
            - run:
                command: git push --follow-tags origin staging

workflows:
  test-build-and-publish:
    jobs:
      - test-build-and-publish:
          <<: *production
